version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    # environment:
    #   - REDIS_URL=redis://redis:6379
    #   - MONGO_URL=mongodb://mongodb:27017
    #   - REPO_TYPE=redis
    networks:
      - urlshortener-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - urlshortener-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 40s
    volumes:
      - mongodb_data:/data/db
    networks:
      - urlshortener-network

networks:
  urlshortener-network:
    driver: bridge

volumes:
  mongodb_data: